# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483f00e8b5358573ba0266f60f962c738c731740d6578ef68510f6b8933650a28cdd39153ae1f2cec3ef8c3b7fc7bf3fa4e510627956c8d1ad9169ff059e94b9

test:
  secret_key_base: 95a8e6263282d89e5450c35ce9c0788efc552340615f2595de4216d667c2d9f67726b11ca6a22ed25a643dfd5925f61291b577cefd6420ce666bff8e8ef38810

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
